<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Identity\Identity.Infrastructure\Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Ordering\Ordering.Infrastructure\Ordering.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Cashier\Cashier.Infrastructure\Cashier.Infrastructure.csproj" />
  </ItemGroup>
</Project>
